name: homework3
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  flutter_boxicons: ^3.0.0
  lottie: ^2.3.2
  get: ^4.6.5
  animate_do: ^3.0.2
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  uni_links: ^0.5.1
  google_fonts: ^4.0.4
  iconsax: ^0.0.8
  google_nav_bar: ^5.0.6
  badges: ^3.1.1
  flutter_staggered_animations: ^1.1.1
  expandable_text: ^2.3.0
  shared_preferences: ^2.2.1
  intl: ^0.19.0
  cloud_firestore: ^4.9.1
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  flutter_image_compress: ^2.0.4
  image_cropper: ^4.0.1
  cached_network_image: ^3.2.3
  photo_view: ^0.14.0
  like_button: ^2.0.5
  http: ^0.13.6
  flutter_slidable: ^3.0.0
  google_maps_flutter: ^2.3.0
  geolocator: ^10.0.1
  geocoding: ^2.1.1
  flutter_svg: ^2.0.5
  url_launcher: ^6.1.11
  fluttertoast: ^8.2.2
  shimmer: ^3.0.0
  dotted_decoration: ^2.0.0
  lit_starfield: ^0.1.1
  flutter_local_notifications: ^16.1.0
  fl_chart: ^0.69.2
  dropdown_button2: ^2.3.9
  flutter_typeahead: ^4.8.0
  flutter_echarts: ^2.5.0
  flutter_stripe: ^11.2.0
  flutter_dotenv: ^5.1.0
  flutter_lints: ^4.0.0

  path: any
  loader_overlay: ^4.0.3
  glassmorphism_ui: ^0.3.0
  bootstrap_grid: ^1.0.4
  go_router: ^14.6.0
  url_strategy: ^0.3.0
  loading_animation_widget: ^1.3.0
  toastification: ^2.3.0
  firebase_core: ^2.32.0
  file_picker: ^8.1.4
  data_table_2: ^2.5.15
  webview_flutter_web: ^0.2.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/bottombar/
    - images/
    - assets/
    - assets/icons/order/
    - assets/icons/home/
    - assets/images/
    - assets/icons/
    - assets/icons/tabbar/bold/
    - assets/icons/tabbar/light/
    - assets/icons/light/
    - assets/icons/bold/
    - assets/icons/products/
    - assets/icons/profile/
    - assets/icons/detail/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # example:
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
